Search.appendIndex(
    [
                {
            "fqsen": "\\sparqlClient\\Connection",
            "name": "Connection",
            "summary": "Description\u0020of\u0020Connection",
            "url": "classes/sparqlClient-Connection.html"
        },                {
            "fqsen": "\\sparqlClient\\Connection\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-Connection.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\Connection\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "classes/sparqlClient-Connection.html#method_query"
        },                {
            "fqsen": "\\sparqlClient\\Connection\u003A\u003AaskQuery\u0028\u0029",
            "name": "askQuery",
            "summary": "",
            "url": "classes/sparqlClient-Connection.html#method_askQuery"
        },                {
            "fqsen": "\\sparqlClient\\Connection\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/sparqlClient-Connection.html#property_client"
        },                {
            "fqsen": "\\sparqlClient\\Connection\u003A\u003A\u0024dataFactory",
            "name": "dataFactory",
            "summary": "",
            "url": "classes/sparqlClient-Connection.html#property_dataFactory"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement",
            "name": "PreparedStatement",
            "summary": "Description\u0020of\u0020PreparedStatement",
            "url": "classes/sparqlClient-PreparedStatement.html"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AbindParam\u0028\u0029",
            "name": "bindParam",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_bindParam"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AbindValue\u0028\u0029",
            "name": "bindValue",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_bindValue"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_execute"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Afetch\u0028\u0029",
            "name": "fetch",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_fetch"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AfetchAll\u0028\u0029",
            "name": "fetchAll",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_fetchAll"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AfetchColumn\u0028\u0029",
            "name": "fetchColumn",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_fetchColumn"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_current"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_key"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_next"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_rewind"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_valid"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AparseQuery\u0028\u0029",
            "name": "parseQuery",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_parseQuery"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AgetQuery\u0028\u0029",
            "name": "getQuery",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_getQuery"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AgetPlaceholderRegex\u0028\u0029",
            "name": "getPlaceholderRegex",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_getPlaceholderRegex"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AescapeValue\u0028\u0029",
            "name": "escapeValue",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_escapeValue"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003APH_POSIT",
            "name": "PH_POSIT",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#constant_PH_POSIT"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003APH_NAMED",
            "name": "PH_NAMED",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#constant_PH_NAMED"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A\u0024statement",
            "name": "statement",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#property_statement"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A\u0024param",
            "name": "param",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#property_param"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#property_query"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#property_connection"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A\u0024ask",
            "name": "ask",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#property_ask"
        },                {
            "fqsen": "\\sparqlClient\\SimpleConnectionInterface",
            "name": "SimpleConnectionInterface",
            "summary": "",
            "url": "classes/sparqlClient-SimpleConnectionInterface.html"
        },                {
            "fqsen": "\\sparqlClient\\SimpleConnectionInterface\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "classes/sparqlClient-SimpleConnectionInterface.html#method_query"
        },                {
            "fqsen": "\\sparqlClient\\SimpleConnectionInterface\u003A\u003AaskQuery\u0028\u0029",
            "name": "askQuery",
            "summary": "",
            "url": "classes/sparqlClient-SimpleConnectionInterface.html#method_askQuery"
        },                {
            "fqsen": "\\sparqlClient\\SimpleConnectionInterface\u003A\u003Aprepare\u0028\u0029",
            "name": "prepare",
            "summary": "",
            "url": "classes/sparqlClient-SimpleConnectionInterface.html#method_prepare"
        },                {
            "fqsen": "\\sparqlClient\\SimpleConnectionInterface\u003A\u003AprepareAsk\u0028\u0029",
            "name": "prepareAsk",
            "summary": "",
            "url": "classes/sparqlClient-SimpleConnectionInterface.html#method_prepareAsk"
        },                {
            "fqsen": "\\sparqlClient\\SparqlException",
            "name": "SparqlException",
            "summary": "Description\u0020of\u0020SparqlException",
            "url": "classes/sparqlClient-SparqlException.html"
        },                {
            "fqsen": "\\sparqlClient\\SparqlRequestException",
            "name": "SparqlRequestException",
            "summary": "Description\u0020of\u0020SparqlRequestException",
            "url": "classes/sparqlClient-SparqlRequestException.html"
        },                {
            "fqsen": "\\sparqlClient\\SparqlRequestException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-SparqlRequestException.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\SparqlRequestException\u003A\u003AgetReqponse\u0028\u0029",
            "name": "getReqponse",
            "summary": "",
            "url": "classes/sparqlClient-SparqlRequestException.html#method_getReqponse"
        },                {
            "fqsen": "\\sparqlClient\\SparqlRequestException\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/sparqlClient-SparqlRequestException.html#property_response"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection",
            "name": "StandardConnection",
            "summary": "SPARQL\u0020endpoint\u0020connection\u0020class\u0020assuming\u0020query\u0020can\u0020be\u0020passed\u0020as\u0020a\u0020\u0022query\u0022\nparameter\u0020of\u0020a\u0020POST\u0020request\u0020\u0028which\u0020isn\u0027t\u0020guaranteed\u0020by\u0020any\u0020SPARQL\u0020standard\nbut\u0020is\u0020a\u0020de\u0020facto\u0020standard\u0020for\u0020SPARQL\u0020database\u0020REST\u0020API\u0020implementations\u0029.",
            "url": "classes/sparqlClient-StandardConnection.html"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method_query"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003AaskQuery\u0028\u0029",
            "name": "askQuery",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method_askQuery"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003Aprepare\u0028\u0029",
            "name": "prepare",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method_prepare"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003AprepareAsk\u0028\u0029",
            "name": "prepareAsk",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method_prepareAsk"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method_getRequest"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#property_url"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#property_connection"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003A\u0024requestFactory",
            "name": "requestFactory",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#property_requestFactory"
        },                {
            "fqsen": "\\sparqlClient\\Statement",
            "name": "Statement",
            "summary": "For\u0020results\u0020data\u0020reference\u0020see\u0020https\u003A\/\/www.w3.org\/TR\/sparql11\u002Dresults\u002Djson\/\nand\u0020https\u003A\/\/w3c.github.io\/rdf\u002Dstar\/cg\u002Dspec\/editors_draft.html\u0023sparql\u002Dstar\u002Dquery\u002Dresults\u002Djson\u002Dformat",
            "url": "classes/sparqlClient-Statement.html"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AfetchAll\u0028\u0029",
            "name": "fetchAll",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_fetchAll"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Afetch\u0028\u0029",
            "name": "fetch",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_fetch"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AfetchColumn\u0028\u0029",
            "name": "fetchColumn",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_fetchColumn"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AmakeTerm\u0028\u0029",
            "name": "makeTerm",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_makeTerm"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_current"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_key"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_next"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_rewind"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_valid"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AbindParam\u0028\u0029",
            "name": "bindParam",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_bindParam"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AbindValue\u0028\u0029",
            "name": "bindValue",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_bindValue"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_execute"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003ALANG_PROP",
            "name": "LANG_PROP",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#constant_LANG_PROP"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_response"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024dataFactory",
            "name": "dataFactory",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_dataFactory"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024iterator",
            "name": "iterator",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_iterator"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024currentRow",
            "name": "currentRow",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_currentRow"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024rowNumber",
            "name": "rowNumber",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_rowNumber"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface",
            "name": "StatementInterface",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003AbindParam\u0028\u0029",
            "name": "bindParam",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_bindParam"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003AbindValue\u0028\u0029",
            "name": "bindValue",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_bindValue"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_execute"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003AfetchAll\u0028\u0029",
            "name": "fetchAll",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_fetchAll"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003Afetch\u0028\u0029",
            "name": "fetch",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_fetch"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003AfetchColumn\u0028\u0029",
            "name": "fetchColumn",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_fetchColumn"
        },                {
            "fqsen": "\\rdfInterface\\BlankNode",
            "name": "BlankNode",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-BlankNode.html"
        },                {
            "fqsen": "\\rdfInterface\\BlankNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-BlankNode.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory",
            "name": "DataFactory",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AnamedNode\u0028\u0029",
            "name": "namedNode",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_namedNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AblankNode\u0028\u0029",
            "name": "blankNode",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_blankNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003Aliteral\u0028\u0029",
            "name": "literal",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_literal"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003AdefaultGraph\u0028\u0029",
            "name": "defaultGraph",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_defaultGraph"
        },                {
            "fqsen": "\\rdfInterface\\DataFactory\u003A\u003Aquad\u0028\u0029",
            "name": "quad",
            "summary": "",
            "url": "classes/rdfInterface-DataFactory.html#method_quad"
        },                {
            "fqsen": "\\rdfInterface\\Dataset",
            "name": "Dataset",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-Dataset.html"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-Dataset.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_copy"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AcopyExcept\u0028\u0029",
            "name": "copyExcept",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_copyExcept"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "Returns\u0020a\u0020new\u0020dataset\u0020being\u0020a\u0020union\u0020of\u0020the\u0020current\u0020one\u0020and\u0020the\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-Dataset.html#method_union"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Axor\u0028\u0029",
            "name": "xor",
            "summary": "Returns\u0020a\u0020dataset\u0020being\u0020a\u0020symmetric\u0020difference\u0020of\u0020the\u0020current\u0020dataset\u0020and\nthe\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-Dataset.html#method_xor"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020quad\u0028s\u0029\u0020to\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_delete"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AdeleteExcept\u0028\u0029",
            "name": "deleteExcept",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-Dataset.html#method_deleteExcept"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AforEach\u0028\u0029",
            "name": "forEach",
            "summary": "Iterates\u0020trough\u0020all\u0020quads\u0020replacing\u0020them\u0020with\u0020a\u0020callback\u0020result.",
            "url": "classes/rdfInterface-Dataset.html#method_forEach"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "Checks\u0020if\u0020a\u0020given\u0020offset\u0020exists.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetExists"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "Returns\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetGet"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Assigns\u0020a\u0020new\u0020value\u0020to\u0020the\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetSet"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "Removes\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-Dataset.html#method_offsetUnset"
        },                {
            "fqsen": "\\rdfInterface\\Dataset\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "Returns\u0020the\u0020current\u0020quad.",
            "url": "classes/rdfInterface-Dataset.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare",
            "name": "DatasetCompare",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-DatasetCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Aevery\u0028\u0029",
            "name": "every",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_every"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Anone\u0028\u0029",
            "name": "none",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_none"
        },                {
            "fqsen": "\\rdfInterface\\DatasetCompare\u003A\u003Aany\u0028\u0029",
            "name": "any",
            "summary": "",
            "url": "classes/rdfInterface-DatasetCompare.html#method_any"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts",
            "name": "DatasetListQuadParts",
            "summary": "Set\u0020of\u0020methods\u0020for\u0020listing\u0020distinct\u0020Terms\u0020being\u0020used\u0020on\u0020a\u0020given\u0020position\nof\u0020dataset\u0020quads.",
            "url": "classes/rdfInterface-DatasetListQuadParts.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts\u003A\u003AlistSubjects\u0028\u0029",
            "name": "listSubjects",
            "summary": "",
            "url": "classes/rdfInterface-DatasetListQuadParts.html#method_listSubjects"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts\u003A\u003AlistPredicates\u0028\u0029",
            "name": "listPredicates",
            "summary": "",
            "url": "classes/rdfInterface-DatasetListQuadParts.html#method_listPredicates"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts\u003A\u003AlistObjects\u0028\u0029",
            "name": "listObjects",
            "summary": "",
            "url": "classes/rdfInterface-DatasetListQuadParts.html#method_listObjects"
        },                {
            "fqsen": "\\rdfInterface\\DatasetListQuadParts\u003A\u003AlistGraphs\u0028\u0029",
            "name": "listGraphs",
            "summary": "",
            "url": "classes/rdfInterface-DatasetListQuadParts.html#method_listGraphs"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce",
            "name": "DatasetMapReduce",
            "summary": "Immutable\u0020edge\u0020processing\u0020methods",
            "url": "classes/rdfInterface-DatasetMapReduce.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "",
            "url": "classes/rdfInterface-DatasetMapReduce.html#method_map"
        },                {
            "fqsen": "\\rdfInterface\\DatasetMapReduce\u003A\u003Areduce\u0028\u0029",
            "name": "reduce",
            "summary": "",
            "url": "classes/rdfInterface-DatasetMapReduce.html#method_reduce"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraph",
            "name": "DefaultGraph",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-DefaultGraph.html"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraph\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-DefaultGraph.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Literal",
            "name": "Literal",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-Literal.html"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020a\u0020new\u0020literal.",
            "url": "classes/rdfInterface-Literal.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Returns\u0020literal\u0027s\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetLang\u0028\u0029",
            "name": "getLang",
            "summary": "Returns\u0020literal\u0027s\u0020language\u0020tag.",
            "url": "classes/rdfInterface-Literal.html#method_getLang"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AgetDatatype\u0028\u0029",
            "name": "getDatatype",
            "summary": "Returns\u0020literal\u0027s\u0020datatype.",
            "url": "classes/rdfInterface-Literal.html#method_getDatatype"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithValue\u0028\u0029",
            "name": "withValue",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withValue"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithLang\u0028\u0029",
            "name": "withLang",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020lang\u0020tag\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withLang"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003AwithDatatype\u0028\u0029",
            "name": "withDatatype",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020with\u0020this\u0020one\u0020with\u0020datatype\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-Literal.html#method_withDatatype"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003ACAST_LEXICAL_FORM",
            "name": "CAST_LEXICAL_FORM",
            "summary": "",
            "url": "classes/rdfInterface-Literal.html#constant_CAST_LEXICAL_FORM"
        },                {
            "fqsen": "\\rdfInterface\\Literal\u003A\u003ACAST_DATATYPE",
            "name": "CAST_DATATYPE",
            "summary": "",
            "url": "classes/rdfInterface-Literal.html#constant_CAST_DATATYPE"
        },                {
            "fqsen": "\\rdfInterface\\NamedNode",
            "name": "NamedNode",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-NamedNode.html"
        },                {
            "fqsen": "\\rdfInterface\\NamedNode\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-NamedNode.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method_parse"
        },                {
            "fqsen": "\\rdfInterface\\Parser\u003A\u003AparseStream\u0028\u0029",
            "name": "parseStream",
            "summary": "",
            "url": "classes/rdfInterface-Parser.html#method_parseStream"
        },                {
            "fqsen": "\\rdfInterface\\Quad",
            "name": "Quad",
            "summary": "Extends\u0020Term\u0020because\u0020of\u0020RDF\u002A",
            "url": "classes/rdfInterface-Quad.html"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "Null\u0020is\u0020not\u0020allowed\u0020to\u0020deal\u0020with\u0020the\u0020ambiguity\u0020between\u0020DefaultGraph\u0020and\nnull\u0020which\u0020mean\u0020the\u0020same\u0020\u0028although\u0020it\u0020should\u0020be\u0020noted\u0020that\u0020all\u0020quads\u0020in\nNamedNode\/BlankNode\u0020graphs\u0020also\u0020belong\u0020to\u0020the\u0020DefaultGraph\u0029.",
            "url": "classes/rdfInterface-Quad.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withSubject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withPredicate"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withObject"
        },                {
            "fqsen": "\\rdfInterface\\Quad\u003A\u003AwithGraph\u0028\u0029",
            "name": "withGraph",
            "summary": "",
            "url": "classes/rdfInterface-Quad.html#method_withGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare",
            "name": "QuadCompare",
            "summary": "Interface\u0020allowing\u0020to\u0020compare\u0020Quads.",
            "url": "classes/rdfInterface-QuadCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompare\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompare.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadIterator",
            "name": "QuadIterator",
            "summary": "",
            "url": "classes/rdfInterface-QuadIterator.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadIterator\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-QuadIterator.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace",
            "name": "RdfNamespace",
            "summary": "",
            "url": "classes/rdfInterface-RdfNamespace.html"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020given\u0020URL\u0020prefix.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Drops\u0020a\u0020given\u0020short\u0020name\u0020and\u0020IRI\u0020prefix\u0020associated\u0020with\u0020it.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_remove"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020a\u0020IRI\u0020prefix\u0020for\u0020a\u0020given\u0020short\u0020name.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_get"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Returns\u0020associative\u0020array\u0020of\u0020all\u0020registered\u0020namespaces\u0020with\u0020array\u0020keys\nbeing\u0020namespace\u0020short\u0020names\u0020and\u0020array\u0020values\u0020containing\u0020URL\u0020prefixes.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_getAll"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Aexpand\u0028\u0029",
            "name": "expand",
            "summary": "Expands\u0020a\u0020shortened\u0020IRI\u0020to\u0020a\u0020NamedNode.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_expand"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespace\u003A\u003Ashorten\u0028\u0029",
            "name": "shorten",
            "summary": "Shortens\u0020provided\u0020NamedNode\u0020IRI.",
            "url": "classes/rdfInterface-RdfNamespace.html#method_shorten"
        },                {
            "fqsen": "\\rdfInterface\\Serializer",
            "name": "Serializer",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method_serialize"
        },                {
            "fqsen": "\\rdfInterface\\Serializer\u003A\u003AserializeStream\u0028\u0029",
            "name": "serializeStream",
            "summary": "",
            "url": "classes/rdfInterface-Serializer.html#method_serializeStream"
        },                {
            "fqsen": "\\rdfInterface\\Term",
            "name": "Term",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-Term.html"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\Term\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-Term.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\TermCompare",
            "name": "TermCompare",
            "summary": "Description\u0020of\u0020TermCompare",
            "url": "classes/rdfInterface-TermCompare.html"
        },                {
            "fqsen": "\\rdfInterface\\TermCompare\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-TermCompare.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\TermCompare\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/rdfInterface-TermCompare.html#method___toString"
        },                {
            "fqsen": "\\rdfInterface\\TermIterator",
            "name": "TermIterator",
            "summary": "",
            "url": "classes/rdfInterface-TermIterator.html"
        },                {
            "fqsen": "\\rdfInterface\\TermIterator\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-TermIterator.html#method_current"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\sparqlClient",
            "name": "sparqlClient",
            "summary": "",
            "url": "namespaces/sparqlclient.html"
        },                {
            "fqsen": "\\rdfInterface",
            "name": "rdfInterface",
            "summary": "",
            "url": "namespaces/rdfinterface.html"
        }            ]
);
