Search.appendIndex(
    [
                {
            "fqsen": "\\sparqlClient\\Connection",
            "name": "Connection",
            "summary": "Description\u0020of\u0020Connection",
            "url": "classes/sparqlClient-Connection.html"
        },                {
            "fqsen": "\\sparqlClient\\Connection\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-Connection.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\Connection\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "classes/sparqlClient-Connection.html#method_query"
        },                {
            "fqsen": "\\sparqlClient\\Connection\u003A\u003A\u0024client",
            "name": "client",
            "summary": "",
            "url": "classes/sparqlClient-Connection.html#property_client"
        },                {
            "fqsen": "\\sparqlClient\\Connection\u003A\u003A\u0024dataFactory",
            "name": "dataFactory",
            "summary": "",
            "url": "classes/sparqlClient-Connection.html#property_dataFactory"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement",
            "name": "PreparedStatement",
            "summary": "Description\u0020of\u0020PreparedStatement",
            "url": "classes/sparqlClient-PreparedStatement.html"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AbindParam\u0028\u0029",
            "name": "bindParam",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_bindParam"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AbindValue\u0028\u0029",
            "name": "bindValue",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_bindValue"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_execute"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Afetch\u0028\u0029",
            "name": "fetch",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_fetch"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AfetchAll\u0028\u0029",
            "name": "fetchAll",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_fetchAll"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AfetchColumn\u0028\u0029",
            "name": "fetchColumn",
            "summary": "Returns\u0020a\u0020first\u0020column\u0020of\u0020the\u0020next\u0020results\u0020row.",
            "url": "classes/sparqlClient-PreparedStatement.html#method_fetchColumn"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_current"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_key"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_next"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_rewind"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_valid"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AparseQuery\u0028\u0029",
            "name": "parseQuery",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_parseQuery"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AgetQuery\u0028\u0029",
            "name": "getQuery",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_getQuery"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AgetPlaceholderRegex\u0028\u0029",
            "name": "getPlaceholderRegex",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_getPlaceholderRegex"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003AescapeValue\u0028\u0029",
            "name": "escapeValue",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#method_escapeValue"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003APH_POSIT",
            "name": "PH_POSIT",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#constant_PH_POSIT"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003APH_NAMED",
            "name": "PH_NAMED",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#constant_PH_NAMED"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A\u0024statement",
            "name": "statement",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#property_statement"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A\u0024param",
            "name": "param",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#property_param"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#property_query"
        },                {
            "fqsen": "\\sparqlClient\\PreparedStatement\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/sparqlClient-PreparedStatement.html#property_connection"
        },                {
            "fqsen": "\\sparqlClient\\SimpleConnectionInterface",
            "name": "SimpleConnectionInterface",
            "summary": "",
            "url": "classes/sparqlClient-SimpleConnectionInterface.html"
        },                {
            "fqsen": "\\sparqlClient\\SimpleConnectionInterface\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "classes/sparqlClient-SimpleConnectionInterface.html#method_query"
        },                {
            "fqsen": "\\sparqlClient\\SimpleConnectionInterface\u003A\u003Aprepare\u0028\u0029",
            "name": "prepare",
            "summary": "",
            "url": "classes/sparqlClient-SimpleConnectionInterface.html#method_prepare"
        },                {
            "fqsen": "\\sparqlClient\\SparqlException",
            "name": "SparqlException",
            "summary": "Description\u0020of\u0020SparqlException",
            "url": "classes/sparqlClient-SparqlException.html"
        },                {
            "fqsen": "\\sparqlClient\\SparqlRequestException",
            "name": "SparqlRequestException",
            "summary": "Description\u0020of\u0020SparqlRequestException",
            "url": "classes/sparqlClient-SparqlRequestException.html"
        },                {
            "fqsen": "\\sparqlClient\\SparqlRequestException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-SparqlRequestException.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\SparqlRequestException\u003A\u003AgetReqponse\u0028\u0029",
            "name": "getReqponse",
            "summary": "",
            "url": "classes/sparqlClient-SparqlRequestException.html#method_getReqponse"
        },                {
            "fqsen": "\\sparqlClient\\SparqlRequestException\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/sparqlClient-SparqlRequestException.html#property_response"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection",
            "name": "StandardConnection",
            "summary": "SPARQL\u0020endpoint\u0020connection\u0020class\u0020assuming\u0020query\u0020can\u0020be\u0020passed\u0020as\u0020a\u0020\u0022query\u0022\nparameter\u0020of\u0020a\u0020POST\u0020request\u0020\u0028which\u0020isn\u0027t\u0020guaranteed\u0020by\u0020any\u0020SPARQL\u0020standard\nbut\u0020is\u0020a\u0020de\u0020facto\u0020standard\u0020for\u0020SPARQL\u0020database\u0020REST\u0020API\u0020implementations\u0029.",
            "url": "classes/sparqlClient-StandardConnection.html"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method_query"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003Aprepare\u0028\u0029",
            "name": "prepare",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method_prepare"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#method_getRequest"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#property_url"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#property_connection"
        },                {
            "fqsen": "\\sparqlClient\\StandardConnection\u003A\u003A\u0024requestFactory",
            "name": "requestFactory",
            "summary": "",
            "url": "classes/sparqlClient-StandardConnection.html#property_requestFactory"
        },                {
            "fqsen": "\\sparqlClient\\Statement",
            "name": "Statement",
            "summary": "For\u0020results\u0020data\u0020reference\u0020see\u0020https\u003A\/\/www.w3.org\/TR\/sparql11\u002Dresults\u002Djson\/\nand\u0020https\u003A\/\/w3c.github.io\/rdf\u002Dstar\/cg\u002Dspec\/editors_draft.html\u0023sparql\u002Dstar\u002Dquery\u002Dresults\u002Djson\u002Dformat",
            "url": "classes/sparqlClient-Statement.html"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AgetAcceptHeader\u0028\u0029",
            "name": "getAcceptHeader",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_getAcceptHeader"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method___construct"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AfetchAll\u0028\u0029",
            "name": "fetchAll",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_fetchAll"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Afetch\u0028\u0029",
            "name": "fetch",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_fetch"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AfetchColumn\u0028\u0029",
            "name": "fetchColumn",
            "summary": "Returns\u0020a\u0020first\u0020column\u0020of\u0020the\u0020next\u0020results\u0020row.",
            "url": "classes/sparqlClient-Statement.html#method_fetchColumn"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AmakeTerm\u0028\u0029",
            "name": "makeTerm",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_makeTerm"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_current"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_key"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_next"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_rewind"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_valid"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AbindParam\u0028\u0029",
            "name": "bindParam",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_bindParam"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AbindValue\u0028\u0029",
            "name": "bindValue",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_bindValue"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#method_execute"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AgetJsonIterator\u0028\u0029",
            "name": "getJsonIterator",
            "summary": "Parses\u0020a\u0020JSON\u0020SPARQL\u0020response\u0020into\u0020rows.",
            "url": "classes/sparqlClient-Statement.html#method_getJsonIterator"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AgetSepIterator\u0028\u0029",
            "name": "getSepIterator",
            "summary": "Parses\u0020a\u0020CSV\/TSV\u0020SPARQL\u0020response\u0020into\u0020rows.",
            "url": "classes/sparqlClient-Statement.html#method_getSepIterator"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AgetXmlIterator\u0028\u0029",
            "name": "getXmlIterator",
            "summary": "Parses\u0020an\u0020XML\u0020SPARQL\u0020response\u0020into\u0020rows.",
            "url": "classes/sparqlClient-Statement.html#method_getXmlIterator"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AJSON_LAN",
            "name": "JSON_LAN",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#constant_JSON_LAN"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AXML_LANG",
            "name": "XML_LANG",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#constant_XML_LANG"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AXML_NMSP",
            "name": "XML_NMSP",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#constant_XML_NMSP"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003AXML_CHUNK_SIZE",
            "name": "XML_CHUNK_SIZE",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#constant_XML_CHUNK_SIZE"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_response"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024dataFactory",
            "name": "dataFactory",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_dataFactory"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024iterator",
            "name": "iterator",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_iterator"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024currentRow",
            "name": "currentRow",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_currentRow"
        },                {
            "fqsen": "\\sparqlClient\\Statement\u003A\u003A\u0024rowNumber",
            "name": "rowNumber",
            "summary": "",
            "url": "classes/sparqlClient-Statement.html#property_rowNumber"
        },                {
            "fqsen": "\\sparqlClient\\BindingElement",
            "name": "BindingElement",
            "summary": "",
            "url": "classes/sparqlClient-BindingElement.html"
        },                {
            "fqsen": "\\sparqlClient\\BindingElement\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/sparqlClient-BindingElement.html#property_name"
        },                {
            "fqsen": "\\sparqlClient\\BindingElement\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/sparqlClient-BindingElement.html#property_type"
        },                {
            "fqsen": "\\sparqlClient\\BindingElement\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/sparqlClient-BindingElement.html#property_value"
        },                {
            "fqsen": "\\sparqlClient\\BindingElement\u003A\u003A\u0024datatype",
            "name": "datatype",
            "summary": "",
            "url": "classes/sparqlClient-BindingElement.html#property_datatype"
        },                {
            "fqsen": "\\sparqlClient\\BindingElement\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/sparqlClient-BindingElement.html#property_subject"
        },                {
            "fqsen": "\\sparqlClient\\BindingElement\u003A\u003A\u0024predicate",
            "name": "predicate",
            "summary": "",
            "url": "classes/sparqlClient-BindingElement.html#property_predicate"
        },                {
            "fqsen": "\\sparqlClient\\BindingElement\u003A\u003A\u0024object",
            "name": "object",
            "summary": "",
            "url": "classes/sparqlClient-BindingElement.html#property_object"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface",
            "name": "StatementInterface",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003AbindParam\u0028\u0029",
            "name": "bindParam",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_bindParam"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003AbindValue\u0028\u0029",
            "name": "bindValue",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_bindValue"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_execute"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003AfetchAll\u0028\u0029",
            "name": "fetchAll",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_fetchAll"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003Afetch\u0028\u0029",
            "name": "fetch",
            "summary": "",
            "url": "classes/sparqlClient-StatementInterface.html#method_fetch"
        },                {
            "fqsen": "\\sparqlClient\\StatementInterface\u003A\u003AfetchColumn\u0028\u0029",
            "name": "fetchColumn",
            "summary": "Returns\u0020a\u0020first\u0020column\u0020of\u0020the\u0020next\u0020results\u0020row.",
            "url": "classes/sparqlClient-StatementInterface.html#method_fetchColumn"
        },                {
            "fqsen": "\\rdfInterface\\BlankNodeInterface",
            "name": "BlankNodeInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-BlankNodeInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface",
            "name": "DataFactoryInterface",
            "summary": "",
            "url": "classes/rdfInterface-DataFactoryInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003AnamedNode\u0028\u0029",
            "name": "namedNode",
            "summary": "Creates\u0020a\u0020new\u0020RDF\u0020named\u0020node.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_namedNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003AblankNode\u0028\u0029",
            "name": "blankNode",
            "summary": "Creates\u0020a\u0020new\u0020RDF\u0020blank\u0020node.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_blankNode"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003Aliteral\u0028\u0029",
            "name": "literal",
            "summary": "Creates\u0020a\u0020new\u0020RDF\u0020literal.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_literal"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003AdefaultGraph\u0028\u0029",
            "name": "defaultGraph",
            "summary": "Returns\u0020an\u0020RDF\u0020default\u0020graph\u0020object.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_defaultGraph"
        },                {
            "fqsen": "\\rdfInterface\\DataFactoryInterface\u003A\u003Aquad\u0028\u0029",
            "name": "quad",
            "summary": "Creates\u0020a\u0020new\u0020RDF\u0020quad.",
            "url": "classes/rdfInterface-DataFactoryInterface.html#method_quad"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface",
            "name": "DatasetInterface",
            "summary": "Main,\u0020edge\u0028quad\u0029\u0020and\u0020Dataset\u002Doriented\u0020Dataset\u0020API",
            "url": "classes/rdfInterface-DatasetInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Afactory\u0028\u0029",
            "name": "factory",
            "summary": "",
            "url": "classes/rdfInterface-DatasetInterface.html#method_factory"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-DatasetInterface.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_copy"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AcopyExcept\u0028\u0029",
            "name": "copyExcept",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_copyExcept"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "Returns\u0020a\u0020new\u0020dataset\u0020being\u0020a\u0020union\u0020of\u0020the\u0020current\u0020one\u0020and\u0020the\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_union"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Axor\u0028\u0029",
            "name": "xor",
            "summary": "Returns\u0020a\u0020dataset\u0020being\u0020a\u0020symmetric\u0020difference\u0020of\u0020the\u0020current\u0020dataset\u0020and\nthe\u0020\u0024other\u0020one.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_xor"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020quad\u0028s\u0029\u0020to\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_delete"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AdeleteExcept\u0028\u0029",
            "name": "deleteExcept",
            "summary": "In\u002Dplace\u0020removes\u0020quads\u0020from\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_deleteExcept"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AforEach\u0028\u0029",
            "name": "forEach",
            "summary": "Iterates\u0020trough\u0020all\u0020quads\u0020replacing\u0020them\u0020with\u0020a\u0020callback\u0020result.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_forEach"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "Checks\u0020if\u0020a\u0020given\u0020offset\u0020exists.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_offsetExists"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "Returns\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_offsetGet"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Assigns\u0020a\u0020new\u0020value\u0020to\u0020the\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_offsetSet"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "Removes\u0020a\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_offsetUnset"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aevery\u0028\u0029",
            "name": "every",
            "summary": "Checks\u0020if\u0020all\u0020quads\u0020in\u0020the\u0020dataset\u0020match\u0020a\u0020given\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_every"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Anone\u0028\u0029",
            "name": "none",
            "summary": "Checks\u0020if\u0020no\u0020quad\u0020in\u0020the\u0020dataset\u0020matches\u0020a\u0020given\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_none"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Aany\u0028\u0029",
            "name": "any",
            "summary": "Checks\u0020if\u0020any\u0020quad\u0020in\u0020the\u0020dataset\u0020matches\u0020a\u0020given\u0020filter.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_any"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "",
            "url": "classes/rdfInterface-DatasetInterface.html#method_map"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003Areduce\u0028\u0029",
            "name": "reduce",
            "summary": "",
            "url": "classes/rdfInterface-DatasetInterface.html#method_reduce"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AlistSubjects\u0028\u0029",
            "name": "listSubjects",
            "summary": "Fetches\u0020an\u0020iterator\u0020over\u0020unique\u0020set\u0020of\u0020dataset\u0020quad\u0020subjects.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_listSubjects"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AlistPredicates\u0028\u0029",
            "name": "listPredicates",
            "summary": "Fetches\u0020an\u0020iterator\u0020over\u0020unique\u0020set\u0020of\u0020dataset\u0020quad\u0020predicates.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_listPredicates"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AlistObjects\u0028\u0029",
            "name": "listObjects",
            "summary": "Fetches\u0020an\u0020iterator\u0020over\u0020unique\u0020set\u0020of\u0020dataset\u0020quad\u0020objects.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_listObjects"
        },                {
            "fqsen": "\\rdfInterface\\DatasetInterface\u003A\u003AlistGraphs\u0028\u0029",
            "name": "listGraphs",
            "summary": "Fetches\u0020an\u0020iterator\u0020over\u0020unique\u0020set\u0020of\u0020dataset\u0020quad\u0020graphs.",
            "url": "classes/rdfInterface-DatasetInterface.html#method_listGraphs"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface",
            "name": "DatasetNodeInterface",
            "summary": "Node\u002Doriented\u0020graph\u0020API\u0020interface.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Afactory\u0028\u0029",
            "name": "factory",
            "summary": "Creates\u0020a\u0020DatasetNodeInterface\u0020object.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_factory"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AgetDataset\u0028\u0029",
            "name": "getDataset",
            "summary": "The\u0020actual\u0020dataset\u0020\u0028and\u0020not\u0020its\u0020copy\u0029\u0020should\u0020be\u0020returned.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_getDataset"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AgetNode\u0028\u0029",
            "name": "getNode",
            "summary": "",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_getNode"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AwithDataset\u0028\u0029",
            "name": "withDataset",
            "summary": "",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_withDataset"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AwithNode\u0028\u0029",
            "name": "withNode",
            "summary": "",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_withNode"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020quad\u0028s\u0029\u0020to\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Assigns\u0020a\u0020new\u0020value\u0020to\u0020the\u0020quad\u0020matching\u0020the\u0020\u0024offset.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_offsetSet"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_copy"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003AcopyExcept\u0028\u0029",
            "name": "copyExcept",
            "summary": "Creates\u0020a\u0020copy\u0020of\u0020the\u0020dataset.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_copyExcept"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Aunion\u0028\u0029",
            "name": "union",
            "summary": "Only\u0020those\u0020quads\u0020from\u0020\u0024other\u0020which\u0020have\u0020subject\u0020matching\u0020the\u0020DatasetNodeInterface\u0027s\u0020node\u0020are\u0020added.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_union"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Axor\u0028\u0029",
            "name": "xor",
            "summary": "The\u0020resulting\u0020dataset\u0020should\u0020contain\u003A\n\u002D\u0020all\u0020quads\u0020of\u0020the\u0020DatasetNodeInterface\u0020with\u0020subject\u0020other\u0020than\u0020the\u0020node\n\u002D\u0020xor\u0020between\u0020triples\u0020of\u0020the\u0020DatasetNodeInterface\u0020with\u0020subject\u0020being\u0020the\u0020node\n\u0020\u0020and\u0020triples\u0020of\u0020the\u0020\u0024other\u0020with\u0020subject\u0020being\u0020the\u0020node",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_xor"
        },                {
            "fqsen": "\\rdfInterface\\DatasetNodeInterface\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "Quads\u0020with\u0020subject\u0020other\u0020than\u0020DatasetNodeInterface\u0027s\u0020node\u0020should\u0020be\nreturned\u0020untouched.",
            "url": "classes/rdfInterface-DatasetNodeInterface.html#method_map"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraphInterface",
            "name": "DefaultGraphInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-DefaultGraphInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\DefaultGraphInterface\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-DefaultGraphInterface.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface",
            "name": "LiteralInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-LiteralInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Returns\u0020literal\u0027s\u0020value.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AgetLang\u0028\u0029",
            "name": "getLang",
            "summary": "Returns\u0020literal\u0027s\u0020language\u0020tag.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_getLang"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AgetDatatype\u0028\u0029",
            "name": "getDatatype",
            "summary": "Returns\u0020literal\u0027s\u0020datatype.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_getDatatype"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AwithValue\u0028\u0029",
            "name": "withValue",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020given\u0020value.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_withValue"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AwithLang\u0028\u0029",
            "name": "withLang",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020of\u0020this\u0020one\u0020with\u0020a\u0020lang\u0020tag\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_withLang"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003AwithDatatype\u0028\u0029",
            "name": "withDatatype",
            "summary": "Returns\u0020a\u0020new\u0020literal\u0020being\u0020a\u0020copy\u0020with\u0020this\u0020one\u0020with\u0020datatype\u0020set\u0020to\na\u0020given\u0020value.",
            "url": "classes/rdfInterface-LiteralInterface.html#method_withDatatype"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003ACAST_LEXICAL_FORM",
            "name": "CAST_LEXICAL_FORM",
            "summary": "",
            "url": "classes/rdfInterface-LiteralInterface.html#constant_CAST_LEXICAL_FORM"
        },                {
            "fqsen": "\\rdfInterface\\LiteralInterface\u003A\u003ACAST_DATATYPE",
            "name": "CAST_DATATYPE",
            "summary": "",
            "url": "classes/rdfInterface-LiteralInterface.html#constant_CAST_DATATYPE"
        },                {
            "fqsen": "\\rdfInterface\\NamedNodeInterface",
            "name": "NamedNodeInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-NamedNodeInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\ParserInterface",
            "name": "ParserInterface",
            "summary": "",
            "url": "classes/rdfInterface-ParserInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\ParserInterface\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-ParserInterface.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\ParserInterface\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/rdfInterface-ParserInterface.html#method_parse"
        },                {
            "fqsen": "\\rdfInterface\\ParserInterface\u003A\u003AparseStream\u0028\u0029",
            "name": "parseStream",
            "summary": "",
            "url": "classes/rdfInterface-ParserInterface.html#method_parseStream"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface",
            "name": "QuadCompareInterface",
            "summary": "Interface\u0020allowing\u0020to\u0020compare\u0020Quads.",
            "url": "classes/rdfInterface-QuadCompareInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompareInterface.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompareInterface.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompareInterface.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadCompareInterface\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "",
            "url": "classes/rdfInterface-QuadCompareInterface.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface",
            "name": "QuadInterface",
            "summary": "Extends\u0020Term\u0020because\u0020of\u0020RDF\u002A",
            "url": "classes/rdfInterface-QuadInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AgetSubject\u0028\u0029",
            "name": "getSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_getSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AgetPredicate\u0028\u0029",
            "name": "getPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_getPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_getObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AgetGraph\u0028\u0029",
            "name": "getGraph",
            "summary": "Null\u0020is\u0020not\u0020allowed\u0020to\u0020deal\u0020with\u0020the\u0020ambiguity\u0020between\u0020DefaultGraph\u0020and\nnull\u0020which\u0020mean\u0020the\u0020same\u0020\u0028although\u0020it\u0020should\u0020be\u0020noted\u0020that\u0020all\u0020quads\u0020in\nNamedNode\/BlankNode\u0020graphs\u0020also\u0020belong\u0020to\u0020the\u0020DefaultGraph\u0029.",
            "url": "classes/rdfInterface-QuadInterface.html#method_getGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AwithSubject\u0028\u0029",
            "name": "withSubject",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_withSubject"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AwithPredicate\u0028\u0029",
            "name": "withPredicate",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_withPredicate"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AwithObject\u0028\u0029",
            "name": "withObject",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_withObject"
        },                {
            "fqsen": "\\rdfInterface\\QuadInterface\u003A\u003AwithGraph\u0028\u0029",
            "name": "withGraph",
            "summary": "",
            "url": "classes/rdfInterface-QuadInterface.html#method_withGraph"
        },                {
            "fqsen": "\\rdfInterface\\QuadIteratorAggregateInterface",
            "name": "QuadIteratorAggregateInterface",
            "summary": "Description\u0020of\u0020QuadIteratorAggregateInterface",
            "url": "classes/rdfInterface-QuadIteratorAggregateInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadIteratorAggregateInterface\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "Returns\u0020QuadIteratorInterface\u0020iterating\u0020over\u0020dataset\u0027s\u0020quads.",
            "url": "classes/rdfInterface-QuadIteratorAggregateInterface.html#method_getIterator"
        },                {
            "fqsen": "\\rdfInterface\\QuadIteratorInterface",
            "name": "QuadIteratorInterface",
            "summary": "",
            "url": "classes/rdfInterface-QuadIteratorInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\QuadIteratorInterface\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-QuadIteratorInterface.html#method_current"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface",
            "name": "RdfNamespaceInterface",
            "summary": "",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Registers\u0020a\u0020given\u0020URL\u0020prefix.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_add"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Aremove\u0028\u0029",
            "name": "remove",
            "summary": "Drops\u0020a\u0020given\u0020short\u0020name\u0020and\u0020IRI\u0020prefix\u0020associated\u0020with\u0020it.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_remove"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020a\u0020IRI\u0020prefix\u0020for\u0020a\u0020given\u0020short\u0020name.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_get"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Returns\u0020associative\u0020array\u0020of\u0020all\u0020registered\u0020namespaces\u0020with\u0020array\u0020keys\nbeing\u0020namespace\u0020short\u0020names\u0020and\u0020array\u0020values\u0020containing\u0020URL\u0020prefixes.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_getAll"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Aexpand\u0028\u0029",
            "name": "expand",
            "summary": "Expands\u0020a\u0020shortened\u0020IRI\u0020to\u0020a\u0020NamedNode.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_expand"
        },                {
            "fqsen": "\\rdfInterface\\RdfNamespaceInterface\u003A\u003Ashorten\u0028\u0029",
            "name": "shorten",
            "summary": "Shortens\u0020provided\u0020NamedNode\u0020IRI.",
            "url": "classes/rdfInterface-RdfNamespaceInterface.html#method_shorten"
        },                {
            "fqsen": "\\rdfInterface\\SerializerInterface",
            "name": "SerializerInterface",
            "summary": "",
            "url": "classes/rdfInterface-SerializerInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\SerializerInterface\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/rdfInterface-SerializerInterface.html#method___construct"
        },                {
            "fqsen": "\\rdfInterface\\SerializerInterface\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/rdfInterface-SerializerInterface.html#method_serialize"
        },                {
            "fqsen": "\\rdfInterface\\SerializerInterface\u003A\u003AserializeStream\u0028\u0029",
            "name": "serializeStream",
            "summary": "",
            "url": "classes/rdfInterface-SerializerInterface.html#method_serializeStream"
        },                {
            "fqsen": "\\rdfInterface\\TermCompareInterface",
            "name": "TermCompareInterface",
            "summary": "Description\u0020of\u0020TermCompare",
            "url": "classes/rdfInterface-TermCompareInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\TermCompareInterface\u003A\u003Aequals\u0028\u0029",
            "name": "equals",
            "summary": "",
            "url": "classes/rdfInterface-TermCompareInterface.html#method_equals"
        },                {
            "fqsen": "\\rdfInterface\\TermInterface",
            "name": "TermInterface",
            "summary": "Description\u0020of\u0020RdfTerm",
            "url": "classes/rdfInterface-TermInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\TermInterface\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "",
            "url": "classes/rdfInterface-TermInterface.html#method_getValue"
        },                {
            "fqsen": "\\rdfInterface\\TermIteratorInterface",
            "name": "TermIteratorInterface",
            "summary": "",
            "url": "classes/rdfInterface-TermIteratorInterface.html"
        },                {
            "fqsen": "\\rdfInterface\\TermIteratorInterface\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "",
            "url": "classes/rdfInterface-TermIteratorInterface.html#method_current"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\sparqlClient",
            "name": "sparqlClient",
            "summary": "",
            "url": "namespaces/sparqlclient.html"
        },                {
            "fqsen": "\\rdfInterface",
            "name": "rdfInterface",
            "summary": "",
            "url": "namespaces/rdfinterface.html"
        }            ]
);
